## Audio (autoload) — plays the pre-synthesized SFX + jetpack loop + 2 music tracks
## (generated by audio_gen.gd). Mirrors the iOS AudioManager API.
extends Node

const NAMES := ["rifle", "uzi", "shotgun", "sniper", "hit", "explosion", "pickup",
	"capture", "win", "flame", "rocket", "nade_throw", "jet", "music_menu", "music_battle",
	"reload", "step", "click", "swap"]

var sound_on := true
var music_on := true

var _streams := {}
var _sfx: Array[AudioStreamPlayer] = []
var _sfx_i := 0
var _jet: AudioStreamPlayer
var _music: AudioStreamPlayer
var _track := "menu"

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS   # music/SFX keep working while paused
	for n in NAMES:
		var s = null
		for ext in ["ogg", "wav"]:                         # prefer a real .ogg if present (e.g. footsteps)
			var pth := "res://assets/audio/%s.%s" % [n, ext]
			if ResourceLoader.exists(pth):
				s = load(pth)
				break
		if s is AudioStreamWAV and (n == "jet" or n.begins_with("music")):
			s.loop_mode = AudioStreamWAV.LOOP_FORWARD
			s.loop_begin = 0
			s.loop_end = s.data.size() / 2
		_streams[n] = s
	for i in 6:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_sfx.append(p)
	_jet = AudioStreamPlayer.new()
	_jet.stream = _streams.get("jet")
	add_child(_jet)
	_music = AudioStreamPlayer.new()
	add_child(_music)
	sound_on = Settings.sound_on
	music_on = Settings.music_on

func play(name: String, volume_db := 0.0, pitch := 1.0) -> void:
	if not sound_on:
		return
	var s = _streams.get(name)
	if s == null:
		return
	var p := _sfx[_sfx_i]
	_sfx_i = (_sfx_i + 1) % _sfx.size()
	p.stream = s
	p.volume_db = volume_db
	p.pitch_scale = pitch
	p.play()

func set_jet(on: bool) -> void:
	if on and sound_on:
		if not _jet.playing:
			_jet.play()
		_jet.volume_db = -7.0
	else:
		_jet.stop()

func set_sound(on: bool) -> void:
	sound_on = on
	if not on:
		_jet.stop()

func set_music(on: bool) -> void:
	music_on = on
	if on:
		_play_track()
	else:
		_music.stop()

func play_track(track: String) -> void:
	if track != _track:
		_track = track
		_music.stop()
	if music_on:
		_play_track()

func _play_track() -> void:
	var s = _streams.get("music_" + _track)
	if s == null:
		return
	if _music.stream != s or not _music.playing:
		_music.stream = s
		_music.volume_db = -9.0 if _track == "menu" else -13.0
		_music.play()
